routes/admin.py
from routes import *
from models.product import Product
from models.order import Order
from models.user import User
from flask import current_app as app

import qiniu
from config import key

q = qiniu.Auth(key.qiniu_access_key, key.qiniu_secret_key)

main = Blueprint('admin', __name__)


# ------------------------- 产品管理 --------------------------
@main.route('/product/new')
@admin_required
def product_new_page():
    u = current_user()
    return render_template('admin/product_new.html', u=u)


@main.route('/product/new', methods=['POST'])
@admin_required
def product_new():
    u = current_user()
    form = request.form
    status, msgs = Product.valid(form)
    if status is True:
        p = Product.new(form)
        return redirect(url_for('admin.product', uuid=p.uuid))
    else:
        return render_template('admin/product_new.html', msgs=msgs, u=u)


@main.route('/products')
@admin_required
def products():
    u = current_user()
    ms = Product.all()
    ms.reverse()
    return render_template('admin/products.html', ms=ms, u=u)


@main.route('/products', methods=['POST'])
@admin_required
def products_search():
    u = current_user()
    form = request.form
    ms = Product.search_or(form)
    ms.reverse()
    return render_template('admin/products.html', u=u, ms=ms)


@main.route('/product/<uuid>')
@admin_required
def product(uuid):
    u = current_user()
    p = Product.find_one(uuid=uuid)
    policy = {
        'callbackUrl': app.config['QINIU_CALLBACK_URL'],
        'callbackBody': 'filename=$(fname)&filesize=$(fsize)&route=$(x:route)&',
        'mimeLimit': 'image/*',
    }
    t = timestamp()
    qiniu_key = '{}{}_{}.{}'.format(app.config['CDN_PRODUCT_PIC_DIR'], uuid, t, app.config['PRODUCT_PIC_EXT'])
    u.token = q.upload_token(app.config['CDN_BUCKET'], key=qiniu_key, policy=policy)
    u.upload_url = app.config['PIC_UPLOAD_URL']
    u.key = qiniu_key
    u.url = url_for('admin.ajax_pic', uuid=uuid)
    return render_template('admin/product.html', p=p, u=u)


@main.route('/product/<uuid>', methods=['POST'])
@admin_required
def product_update(uuid):
    p = Product.find_one(uuid=uuid)
    form = request.form
    p.update(form)
    return redirect(url_for('admin.product', uuid=p.uuid))


@main.route('/product/picture/url/<uuid>', methods=['POST'])
@admin_required
def set_product_pic_url(uuid):
    p = Product.find_one(uuid=uuid)
    url = request.form.get('file_url')
    p.set_pic_url(url)
    return redirect(url_for('admin.product', uuid=p.uuid))


@main.route('/picture/ajax/<uuid>', methods=['POST'])
@admin_required
def ajax_pic(uuid):
    p = Product.find_one(uuid=uuid)
    qiniu_key = request.form.get('key')
    p.qiniu_pic(qiniu_key)
    return redirect(url_for('admin.product', uuid=p.uuid))


@main.route('/delete/<int:id>')
@admin_required
def product_delete(id):
    # p = Model.get(id)
    # p.delete()
    # TODO 先不让删
    return redirect(url_for('admin.products'))


# ------------------------- 用户管理 --------------------------
@main.route('/users')
@admin_required
def users():
    u = current_user()
    ms = User.all()
    return render_template('admin/users.html', ms=ms, u=u)


@main.route('/users', methods=['POST'])
@admin_required
def users_search():
    u = current_user()
    form = request.form
    ms = User.search_or(form)
    return render_template('admin/users.html', u=u, ms=ms)


@main.route('/user/<int:id>')
@admin_required
def user(id):
    u = current_user()
    m = User.get(id)
    ps = m.get_cart_detail()
    return render_template('admin/user.html', m=m, ps=ps, u=u)


@main.route('/user/delete/<int:id>')
@admin_required
def user_delete(id):
    # m = User.get(id)
    # m.delete()
    # TODO 先不让删
    return redirect(url_for('admin.users'))


@main.route('/user/update/<int:id>', methods=['POST'])
@admin_required
def user_update(id):
    m = User.get(id)
    form = request.form
    m.update_user(form)
    return redirect(url_for('admin.user', id=m.id))


# ------------------------- 订单管理 --------------------------
@main.route('/orders')
@admin_required
def orders():
    u = current_user()
    ms = Order.all()
    ms.reverse()
    return render_template('admin/orders.html', ms=ms, u=u)


@main.route('/orders', methods=['POST'])
@admin_required
def orders_search():
    u = current_user()
    form = request.form
    ms = Order.search_or(form)
    ms.reverse()
    return render_template('admin/orders.html', u=u, ms=ms)


@main.route('/order/<orderNo>')
@admin_required
def order(orderNo):
    u = current_user()
    o = Order.find_one(orderNo=orderNo)
    o.user = User.get(o.user_id)
    return render_template('admin/order.html', o=o, u=u)


@main.route('/order/delivery/<orderNo>')
@admin_required
def order_delivery(orderNo):
    o = Order.find_one(orderNo=orderNo)
    o.delivery()
    return redirect(url_for('admin.orders'))


@main.route('/house')
def house():
    return render_template('house.html')

# @main.route('/root')
# @login_required
# def root_set():
#     root = User.find_one(username='root')
#     root.role = 'admin'
#     root.save()
#     return redirect(url_for('admin.products'))
#
#
# @main.route('/uuid_reset_all')
# @admin_required
# def order_no_reset():
#     os = Order.all()
#     us = User.all()
#     ps = Product.all()
#     for o in os:
#         o.set_uuid('orderNo')
#         o.set_uuid()
#     for u in us:
#         u.set_uuid()
#     for p in ps:
#         p.set_uuid()
#     return redirect(url_for('admin.products'))
#
#
# @main.route('/clear_order_items')
# @admin_required
# def clear_order_items():
#     os = Order.all()
#     for o in os:
#         o.items = []
#         o.save()
#     return redirect(url_for('admin.products'))


# @main.route('/clear_orders')
# @admin_required
# def clear_orders():
#     os = Order.all()
#     for o in os:
#         o.delete()
#     return redirect(url_for('admin.products'))
#
#
# @main.route('/clear_carts')
# @admin_required
# def clear_carts():
#     us = User.all()
#     for u in us:
#         u.cart_clear()
#     return redirect(url_for('admin.products'))

routes/product.py
from . import *
from models.product import Product

main = Blueprint('product', __name__)


@main.route('/detail/<uuid>')
def detail(uuid):
    u = current_user()
    p = Product.find_one(uuid=uuid)

    return render_template('product/detail.html', p=p, u=u)

routes/user.py
from routes import *
from models.user import User
from models.order import Order
from decimal import Decimal
from flask import current_app as app

main = Blueprint('user', __name__)

Model = User


@main.route('/login')
def index():
    return render_template('user/login.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    username = form.get('username', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.index'))
    u = User.find_one(username=username)
    if u is not None and u.validate_login(form):
        session['uid'] = u.id
        return redirect(url_for('index.index'))
    else:
        flash('用户名密码错误', 'warning')
        return redirect(url_for('user.index'))


@main.route('/register')
def register_page():
    return render_template('user/register.html')


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.register'))
    status, msgs = User.valid(form)
    if status is True:
        u = User.new(form)
        u.send_email_verify(u.email)
        session['uid'] = u.id
        flash('验证邮件已发送，请查收', 'info')
        return redirect(url_for('index.index'))
    else:
        for msg in msgs:
            flash(msg, 'warning')
        return redirect(url_for('user.register'))


@main.route('/password/forget')
def forget_password():
    return render_template('user/forget_password.html')


@main.route('/password/forget', methods=['POST'])
def forget_password_send():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.forget_password'))
    r = User.forget_password(form)
    if r:
        flash('密码重置邮件已经发送，请查收邮箱', 'success')
    else:
        flash('用户名或邮箱不匹配', 'warning')
    return redirect(url_for('user.forget_password'))


@main.route('/email/verify/<tb64>')
def email_verify(tb64):
    if User.email_verify(tb64):
        flash('邮箱验证通过', 'success')
    else:
        flash('邮箱验证失败', 'danger')
    return redirect(url_for('user.profile'))


@main.route('/password/forget/verify/<tb64>')
def forget_password_verify(tb64):
    if User.forget_password_verify(tb64):
        flash('重置邮件验证通过', 'success')
        return render_template('user/reset_password.html', tb64=tb64)
    else:
        flash('重置邮件验证失败', 'danger')
        return redirect(url_for('user.index'))


@main.route('/password/reset/<tb64>', methods=['POST'])
def reset_password(tb64):
    password = request.form.get('password', '')
    if User.forget_password_verify(tb64):
        u = User.get_user_by_tb64(tb64)
        u.reset_password(password)
        session['uid'] = u.id
        flash('密码已重置', 'success')
        return redirect(url_for('index.index'))
    else:
        flash('重置邮件验证失败', 'warning')
        return redirect(url_for('user.index'))


@main.route('/profile')
@login_required
def profile():
    cu = current_user()
    return render_template('user/profile.html', u=cu)


@main.route('/profile', methods=['POST'])
@login_required
def profile_update():
    cu = current_user()
    form = request.form
    cu.safe_update_user(form)
    flash('信息已更新', 'success')
    return redirect(url_for('user.profile'))


@main.route('/email/update', methods=['POST'])
@login_required
def update_email():
    u = current_user()
    form = request.form
    new_email = form.get('email', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        return json.dumps({'status': 'warning', 'msg': '验证码错误'})
    if User.has(email=new_email) and User.find_one(email=new_email).uuid != u.uuid:
        return json.dumps({'status': 'warning', 'msg': '该邮箱已被占用'})
    if u.validate_login(form):
        u.send_email_verify(new_email)
        return json.dumps({'status': 'info', 'msg': '已发送验证邮件，请查收'})
    else:
        return json.dumps({'status': 'warning', 'msg': '密码错误'})


@main.route('/avatar/upload', methods=['POST'])
@login_required
def avatar():
    u = current_user()
    avatar = request.files['avatar']
    u.update_avatar(avatar)
    return redirect(url_for('.profile'))


@main.route('/cart/add', methods=['GET'])
@login_required
def cart_add():
    u = current_user()
    product_uuid = request.args.get('product_uuid', None)
    u.cart_add(product_uuid)
    return redirect(url_for('user.cart'))


@main.route('/cart/sub', methods=['GET'])
@login_required
def cart_sub():
    u = current_user()
    product_uuid = request.args.get('product_uuid', None)
    u.cart_sub(product_uuid)
    return redirect(url_for('user.cart'))


@main.route('/cart')
@login_required
def cart():
    u = current_user()
    ps = u.get_cart_detail()
    u.count_num = u.get_cart_count()
    u.count_price = str(sum([Decimal(p.sum) for p in ps]))
    return render_template('user/cart.html', u=u, ps=ps)


@main.route('/cart/clear')
@login_required
def cart_clear():
    u = current_user()
    u.cart_clear()
    return redirect(url_for('user.cart'))


@main.route('/logout')
@login_required
def logout():
    p = session.pop('uid')
    print('logout: pop uid', p)
    flash('账号已安全退出', 'success')
    return redirect(url_for('index.index'))


@main.route('/order/check')
@login_required
@cart_not_empty_required
@email_verify_required
def check_order():
    u = current_user()
    u.add = u.get_default_add()
    ps = u.get_cart_detail()
    u.count_num = u.get_cart_count()
    u.count_price = str(sum([Decimal(p.sum) for p in ps]))
    return render_template('user/check_order.html', u=u, ps=ps)


@main.route('/pay', methods=['POST'])
@login_required
@cart_not_empty_required
@email_verify_required
def pay():
    u = current_user()
    form = request.form
    u.buy(form)
    return redirect(url_for('user.orders'))


@main.route('/orders')
@login_required
def orders():
    u = current_user()
    os = u.orders()
    return render_template('user/orders.html', os=os, u=u)


@main.route('/order/<orderNo>')
@login_required
def order(orderNo):
    u = current_user()
    o = Order.find_one(orderNo=orderNo)
    if o is not None and o.user_id == u.id:
        return render_template('user/order.html', o=o, u=u)
    else:
        return redirect(url_for('user.orders'))


@main.route('/address')
@login_required
def address():
    cu = current_user()
    address_id = int(request.args.get('id', -1))
    if address_id >= 0:
        address_editing = safe_list_get(cu.add_list, address_id, None)
        if address_editing:
            address_editing['id'] = address_id
    else:
        address_editing = None
    return render_template('user/address.html', u=cu, a=address_editing)


@main.route('/address', methods=['POST'])
@login_required
def address_add():
    cu = current_user()
    form = request.form
    add = form.to_dict()
    cu.add_list.append(add)
    cu.save()
    return render_template('user/address.html', u=cu)


@main.route('/address/update/<int:id>', methods=['POST'])
@login_required
def address_update(id):
    cu = current_user()
    form = request.form
    add = form.to_dict()
    try:
        cu.add_list[id] = add
        cu.save()
    except IndexError:
        pass
    return redirect(url_for('user.address'))


@main.route('/address/default/<int:id>')
@login_required
def address_default(id):
    cu = current_user()
    cu.add_default = id
    cu.save()
    return redirect(url_for('user.address'))

templates/admin_order.html
{% extends 'base.html' %}
{% block body %}
<div class="">
    <h1>Order Manage</h1>
</div>
<form class="navbar-form " action="{{ url_for('admin.order_list_search')}}" method="post">
    <input type="text" class="form-control" name="orderNo" placeholder="按订单号检索">
    <input type="text" class="form-control" name="username" placeholder="按用户名检索">
    <button type="submit" class="btn btn-default">Search</button>
</form>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="th-col-2">订单号</th>
            <th class="th-col-2">用户</th>
            <th class="th-col-2">金额</th>
            <th class="th-col-2">发货</th>
            <th class="th-col-2">下单时间</th>
        </tr>
    </thead>
    <tbody>
        {% for m in ms %}
        <tr data-id={{ m.orderNo }}>
            <td>
                <a href="{{ url_for('admin.order_edit', orderNo=m.orderNo) }}">{{ m.orderNo }}</a>
            </td>
            <td>
                <a href="{{ url_for('admin.user_edit', id=m.user_id) }}">{{ m.username }}</a>
            </td>
            <td>{{ m.amount }}</td>
            <td>
                {% if m.status == 'pending' %}
                <a href="{{ url_for('admin.order_delivery', orderNo=m.orderNo) }}">发货</a>
                {% else %}
                已发货
                {% endif %}
            </td>
            <td>{{ m.ct }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/admin_user.html
{% extends 'base.html' %}
{% block body %}
<div class="">
    <h1>User Manage</h1>

</div>
<form class="navbar-form " action="{{ url_for('admin.user_list_search')}}" method="post">
    <input type="text" class="form-control" name="username" placeholder="按用户名检索">
    <input type="text" class="form-control" name="uuid" placeholder="按uuid检索">
    <button type="submit" class="btn btn-default">Search</button>
</form>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="th-col-2">用户</th>
            <th class="th-col-2">uuid</th>
            <th class="th-col-2">权限</th>
            <th class="th-col-2">操作</th>
        </tr>
    </thead>
    <tbody>
        {% for m in ms %}
        <tr data-id={{ m.id }}>
            <td>
                <a href="{{ url_for('admin.user_edit', id=m.id) }}">{{ m.username }}</a>
            </td>

            <td>{{ m.uuid }}</td>
            <td>{{ m.role }}</td>
            <td>
                <a href="{{ url_for('admin.user_delete', id=m.id) }}">删除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>N.I.L.E.</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery.form/4.2.1/jquery.form.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body data-channel="public">
<div class="container alert-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">×</span></button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
<script>
    $(document).ready(function () {
            $('.alert').delay(3000).fadeOut(600);
        }
    );
</script>
{% block head %}
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#base-nav-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('index.index') }}">首页</a>
            </div>

            <div class="collapse navbar-collapse" id="base-nav-collapse-1">
                <form class="navbar-form navbar-left" action="{{ url_for('index.index') }}" method="post">
                    <div class="form-group">
                        <input type="text" class="form-control" name="search">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if u %}
                        {% if u.role=='admin' %}
                            <li class="dropdown">
                                <a class="dropdown-toggle"
                                   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    管理员: {{ u.role }}<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a class="" href="{{ url_for('admin.products') }}">产品管理</a></li>
                                    <li><a class="" href="{{ url_for('admin.users') }}">用户管理</a></li>
                                    <li><a class="" href="{{ url_for('admin.orders') }}">订单管理</a></li>
                                </ul>
                            </li>
                        {% endif %}
                        <li class="dropdown">
                            <a class="dropdown-toggle"
                               data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                欢迎，{{ u.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a class="" href="{{ url_for('user.profile') }}">个人资料</a></li>
                                <li><a class="" href="{{ url_for('user.orders') }}">我的订单</a></li>
                                <li><a class="" href="{{ url_for('user.address') }}">地址管理</a></li>
                            </ul>
                        </li>
                        <li><a class="block-center" href="{{ url_for('user.cart') }}">购物车
                            <span class="badge class-cart-count">{{ u.get_cart_count() }}</span>
                        </a></li>
                        <li>
                            <a class="block-center" href="{{ url_for('user.logout') }}">
                                <span class="glyphicon glyphicon-off"></span> 登出
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <a class="block-center" href="{{ url_for('user.login') }}">
                                <span class="glyphicon glyphicon-log-in"></span> 登录
                            </a>
                        </li>
                        <li>
                            <a class="block-center" href="{{ url_for('user.register') }}">
                                <span class="glyphicon glyphicon-user"></span> 注册
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

<div class="main container page-wrap">
    {% block body %}
    {% endblock %}
</div>

{% block foot %}
    <footer class="bs-docs-footer">
        <div class="container">
            <ul class="footer-links">
                <li><a href="#">GitHub 仓库</a></li>
                <li><a href="#">协议</a></li>
                <li><a href="#">加入我们</a></li>
                <li><a href="#">关于</a></li>
            </ul>
            <p>
                Designed and built with all the love in the world by @Suzumiya.
            </p>
            <p>
                本项目源码受 MIT 开源协议保护.
            </p>
        </div>

    </footer>
{% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block body %}
<h1>Product List</h1>
<div class="container">
    {% for p in ps %}
    <div data-id={{ p.uuid }} class="row product-item list-item">
        <div class="col-xs-3 col-sm-2 list-pic-fix">
            <a href="{{ url_for('product.detail', uuid=p.uuid) }}">
                <img src="{{ p.pic }}" class="product-pic-m">
            </a>
        </div>
        <div class="col-xs-5 col-sm-6">
            <a href="{{ url_for('product.detail', uuid=p.uuid) }}">{{ p.name }}</a>
        </div>
        <div class="col-xs-4 col-sm-2">
            <span class="count_num">￥ {{ p.price }}</span>
        </div>
        <div class="col-xs-4 col-sm-2 right">
            <a class="btn btn-danger" href="{{ url_for('user.cart_add', product_uuid=p.uuid)}}">加入购物车</a>
        </div>

    </div>
    {% endfor %}
</div>
{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}
{% block body %}
<ol class="breadcrumb">
    <li><a href="{{ url_for('index.index') }}">Product List</a></li>
    <li class="active">Detail</li>
</ol>

<div hidden>
    <textarea id="text-input">{{ p.detail }}</textarea>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-3">
        <img src="{{ p.pic }}"  class="product-pic-l" id=id-pic-view>
    </div>
    <div class="col-xs-12 col-sm-8">
        <h3>{{ p.name }}</h3>
        <h3 class="count_num">￥{{ p.price }}</h3>
        <a class="btn btn-danger" href="{{ url_for('user.cart_add', product_id=p.id)}}">加入购物车</a>
    </div>

</div>

<div id="preview"> </div>

<script src="https://cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
<script>
function Editor(input, preview) {
    this.update = function () {
        preview.innerHTML = markdown.toHTML(input.value);
    };
    input.editor = this;
    this.update();
}
const log = function log(){
  console.log.apply(console, arguments);
}

new Editor(document.getElementById("text-input"), document.getElementById("preview"));
</script>
{% endblock %}

templates/user_address.html
{% extends 'base.html' %}
{% block body %}
<div>
    <h1>Address</h1>
    {% if not a %}
    <button type="button" class="btn btn-danger" id="id-button-address-new">新增地址</button>
    {% endif %}
</div>
<br>
<div id="id-div-address-new" class="div-form panel panel-primary"
{% if (u.add_list|count)>0 %}
hidden="hidden"
{% endif %}
>
    <div class="panel-body">
        <form method=POST enctype=multipart/form-data action="{{ url_for('user.address') }}">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <label for="id-name">收件人姓名</label>
                    <input class="form-control" name="name" id=id-name >
                </div>
                <div class="col-xs-12 col-sm-6">
                    <label for="id-phone">联系电话</label>
                    <input class="form-control" name=phone id=id-phone >
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <label for="id-add">具体地址</label>
                    <input class="form-control" name=address id=id-add >
                </div>
            </div>
            <br>
            <button class="btn btn-success btn-block" >创建新地址</button>
        </form>
    </div>
<br>
</div>
{% if a %}
<div class="div-form panel panel-primary">
    <div class="panel-body">
        <form method=POST action="{{ url_for('user.address_update', id=a.id)}}">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <label for="id-name-update">收件人姓名</label>
                    <input class="form-control" name="name" id=id-name-update value="{{ a.name }}">
                </div>
                <div class="col-xs-12 col-sm-6">
                    <label for="id-phone-update">联系电话</label>
                    <input class="form-control" name=phone id=id-phone-update value="{{ a.phone }}">
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <label for="id-add-update">具体地址</label>
                    <input class="form-control" name=address id=id-add-update value="{{ a.address }}">
                </div>
            </div>
            <br>
            <button class="btn btn-success btn-block" >更新地址</button>
        </form>
    </div>
    <br>
</div>
{% endif %}
<div class="container">
    {% for add in u.add_list %}
    <div class="row panel panel-default">
        <div class="panel-heading">
            <span class="panel-heading-time {% if loop.index0 == u.add_default %} add-default {% endif %}">{{ add.name }}</span>
            <a class="right address-edit-button"
            href="{{ url_for('user.address', id=loop.index0)}}"><span>[编辑]</span></a>
            {% if loop.index0 == u.add_default %}
            <a class="right add-default"><span class="glyphicon glyphicon-star-empty"></span> 默认地址</a>
            {% else %}
            <a class="right" href="{{ url_for('user.address_default', id=loop.index0)}}"><span>[设为默认地址]</span></a>
            {% endif %}
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">姓名：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{ add.name }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">电话：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{ add.phone }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">地址：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{add.address}}
                </div>
            </div>

        </div>

    </div>
    {% endfor %}
</div>
<script>
    $('#id-button-address-new').click(function(){
        $('#id-div-address-new').toggle()
    })
</script>
{% endblock %}

templates/user_profile.html
{% extends 'base.html' %}
{% block body %}
<div>
    <h1>Profile</h1>
</div>
<div class="div-form sign-flow" >
    <form method=POST enctype=multipart/form-data action="{{ url_for('user.profile_update') }}">
        <label for="id-name">用户名</label>
        <input class="form-control" name="username" id=id-name value="{{ u.username }}">
        <label for="id-password">修改密码</label>
        <input class="form-control" name=password id=id-password >
        <label for="id-re-password">重复密码</label>
        <input class="form-control" name=re_password id=id-re-password >
        <hr>
        <button class="btn btn-success btn-block">更新</button>
    </form>

</div>
{% endblock %}