models/order.py
from . import MongoModel
from enum import Enum


class Status(Enum):
    pending = 1
    payed = 2
    delivery = 3
    finish = 4


class Order(MongoModel):
    @classmethod
    def _fields(cls):
        fields = [
            ('orderNo', str, ''),
            ('address', dict, {}),
            ('payment', str, ''),
            ('items', list, []),
            ('amount', str, ''),
            ('user_id', int, -1),
            ('user_uuid', str, ''),
            ('username', str, ''),
            ('comment', str, ''),
            ('status', str, ''),
        ]
        fields.extend(super()._fields())
        return fields

    @classmethod
    def new(cls, form):
        m = super().new(form)
        m.set_uuid('orderNo')
        m.status = 'pending'
        m.save()
        return m

    def payed(self):
        self.status = 'payed'
        self.save()
        return self

    def delivery(self):
        self.status = 'delivery'
        self.save()
        return self

    def finish(self):
        self.status = 'finish'
        self.save()
        return self

routes/user.py
from routes import *
from models.user import User
from models.order import Order
from decimal import Decimal
from flask import current_app as app

main = Blueprint('user', __name__)

Model = User


@main.route('/login')
def index():
    return render_template('user/login.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    username = form.get('username', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.index'))
    u = User.find_one(username=username)
    if u is not None and u.validate_login(form):
        session['uid'] = u.id
        return redirect(url_for('index.index'))
    else:
        flash('用户名密码错误', 'warning')
        return redirect(url_for('user.index'))


@main.route('/register')
def register_page():
    return render_template('user/register.html')


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.register'))
    status, msgs = User.valid(form)
    if status is True:
        u = User.new(form)
        u.send_email_verify(u.email)
        session['uid'] = u.id
        flash('验证邮件已发送，请查收', 'info')
        return redirect(url_for('index.index'))
    else:
        for msg in msgs:
            flash(msg, 'warning')
        return redirect(url_for('user.register'))


@main.route('/password/forget')
def forget_password():
    return render_template('user/forget_password.html')


@main.route('/password/forget', methods=['POST'])
def forget_password_send():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.forget_password'))
    r = User.forget_password(form)
    if r:
        flash('密码重置邮件已经发送，请查收邮箱', 'success')
    else:
        flash('用户名或邮箱不匹配', 'warning')
    return redirect(url_for('user.forget_password'))


@main.route('/email/verify/<tb64>')
def email_verify(tb64):
    if User.email_verify(tb64):
        flash('邮箱验证通过', 'success')
    else:
        flash('邮箱验证失败', 'danger')
    return redirect(url_for('user.profile'))


@main.route('/password/forget/verify/<tb64>')
def forget_password_verify(tb64):
    if User.forget_password_verify(tb64):
        flash('重置邮件验证通过', 'success')
        return render_template('user/reset_password.html', tb64=tb64)
    else:
        flash('重置邮件验证失败', 'danger')
        return redirect(url_for('user.index'))


@main.route('/password/reset/<tb64>', methods=['POST'])
def reset_password(tb64):
    password = request.form.get('password', '')
    if User.forget_password_verify(tb64):
        u = User.get_user_by_tb64(tb64)
        u.reset_password(password)
        session['uid'] = u.id
        flash('密码已重置', 'success')
        return redirect(url_for('index.index'))
    else:
        flash('重置邮件验证失败', 'warning')
        return redirect(url_for('user.index'))


@main.route('/profile')
@login_required
def profile():
    cu = current_user()
    return render_template('user/profile.html', u=cu)


@main.route('/profile', methods=['POST'])
@login_required
def profile_update():
    cu = current_user()
    form = request.form
    cu.safe_update_user(form)
    flash('信息已更新', 'success')
    return redirect(url_for('user.profile'))


@main.route('/email/update', methods=['POST'])
@login_required
def update_email():
    u = current_user()
    form = request.form
    new_email = form.get('email', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.get('captcha', 'no captcha!'):
        return json.dumps({'status': 'warning', 'msg': '验证码错误'})
    if User.has(email=new_email) and User.find_one(email=new_email).uuid != u.uuid:
        return json.dumps({'status': 'warning', 'msg': '该邮箱已被占用'})
    if u.validate_login(form):
        u.send_email_verify(new_email)
        return json.dumps({'status': 'info', 'msg': '已发送验证邮件，请查收'})
    else:
        return json.dumps({'status': 'warning', 'msg': '密码错误'})


@main.route('/avatar/upload', methods=['POST'])
@login_required
def avatar():
    u = current_user()
    avatar = request.files['avatar']
    u.update_avatar(avatar)
    return redirect(url_for('.profile'))


@main.route('/cart/add', methods=['GET'])
@login_required
def cart_add():
    u = current_user()
    product_uuid = request.args.get('product_uuid', None)
    u.cart_add(product_uuid)
    return redirect(url_for('user.cart'))


@main.route('/cart/sub', methods=['GET'])
@login_required
def cart_sub():
    u = current_user()
    product_uuid = request.args.get('product_uuid', None)
    u.cart_sub(product_uuid)
    return redirect(url_for('user.cart'))


@main.route('/cart')
@login_required
def cart():
    u = current_user()
    ps = u.get_cart_detail()
    u.count_num = u.get_cart_count()
    u.count_price = str(sum([Decimal(p.sum) for p in ps]))
    return render_template('user/cart.html', u=u, ps=ps)


@main.route('/cart/clear')
@login_required
def cart_clear():
    u = current_user()
    u.cart_clear()
    return redirect(url_for('user.cart'))


@main.route('/logout')
@login_required
def logout():
    p = session.pop('uid')
    print('logout: pop uid', p)
    flash('账号已安全退出', 'success')
    return redirect(url_for('index.index'))


@main.route('/order/check')
@login_required
@cart_not_empty_required
@email_verify_required
def check_order():
    u = current_user()
    u.add = u.get_default_add()
    ps = u.get_cart_detail()
    u.count_num = u.get_cart_count()
    u.count_price = str(sum([Decimal(p.sum) for p in ps]))
    return render_template('user/check_order.html', u=u, ps=ps)


@main.route('/pay', methods=['POST'])
@login_required
@cart_not_empty_required
@email_verify_required
def pay():
    u = current_user()
    form = request.form
    u.buy(form)
    return redirect(url_for('user.orders'))


@main.route('/orders')
@login_required
def orders():
    u = current_user()
    os = u.orders()
    return render_template('user/orders.html', os=os, u=u)


@main.route('/order/<orderNo>')
@login_required
def order(orderNo):
    u = current_user()
    o = Order.find_one(orderNo=orderNo)
    if o is not None and o.user_id == u.id:
        return render_template('user/order.html', o=o, u=u)
    else:
        return redirect(url_for('user.orders'))


@main.route('/address')
@login_required
def address():
    cu = current_user()
    address_id = int(request.args.get('id', -1))
    if address_id >= 0:
        address_editing = safe_list_get(cu.add_list, address_id, None)
        if address_editing:
            address_editing['id'] = address_id
    else:
        address_editing = None
    return render_template('user/address.html', u=cu, a=address_editing)


@main.route('/address', methods=['POST'])
@login_required
def address_add():
    cu = current_user()
    form = request.form
    add = form.to_dict()
    cu.add_list.append(add)
    cu.save()
    return render_template('user/address.html', u=cu)


@main.route('/address/update/<int:id>', methods=['POST'])
@login_required
def address_update(id):
    cu = current_user()
    form = request.form
    add = form.to_dict()
    try:
        cu.add_list[id] = add
        cu.save()
    except IndexError:
        pass
    return redirect(url_for('user.address'))


@main.route('/address/default/<int:id>')
@login_required
def address_default(id):
    cu = current_user()
    cu.add_default = id
    cu.save()
    return redirect(url_for('user.address'))

templates/user/address.html
{% extends 'base.html' %}
{% block body %}
<div>
    <h1>Address</h1>
    {% if not a %}
    <button type="button" class="btn btn-danger" id="id-button-address-new">新增地址</button>
    {% endif %}
</div>
<br>
<div id="id-div-address-new" class="div-form panel panel-primary"
{% if (u.add_list|count)>0 %}
hidden="hidden"
{% endif %}
>
    <div class="panel-body">
        <form method=POST enctype=multipart/form-data action="{{ url_for('user.address') }}">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <label for="id-name">收件人姓名</label>
                    <input class="form-control" name="name" id=id-name >
                </div>
                <div class="col-xs-12 col-sm-6">
                    <label for="id-phone">联系电话</label>
                    <input class="form-control" name=phone id=id-phone >
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <label for="id-add">具体地址</label>
                    <input class="form-control" name=address id=id-add >
                </div>
            </div>
            <br>
            <button class="btn btn-success btn-block" >创建新地址</button>
        </form>
    </div>
<br>
</div>
{% if a %}
<div class="div-form panel panel-primary">
    <div class="panel-body">
        <form method=POST action="{{ url_for('user.address_update', id=a.id)}}">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <label for="id-name-update">收件人姓名</label>
                    <input class="form-control" name="name" id=id-name-update value="{{ a.name }}">
                </div>
                <div class="col-xs-12 col-sm-6">
                    <label for="id-phone-update">联系电话</label>
                    <input class="form-control" name=phone id=id-phone-update value="{{ a.phone }}">
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <label for="id-add-update">具体地址</label>
                    <input class="form-control" name=address id=id-add-update value="{{ a.address }}">
                </div>
            </div>
            <br>
            <button class="btn btn-success btn-block" >更新地址</button>
        </form>
    </div>
    <br>
</div>
{% endif %}
<div class="container">
    {% for add in u.add_list %}
    <div class="row panel panel-default">
        <div class="panel-heading">
            <span class="panel-heading-time {% if loop.index0 == u.add_default %} add-default {% endif %}">{{ add.name }}</span>
            <a class="right address-edit-button"
            href="{{ url_for('user.address', id=loop.index0)}}"><span>[编辑]</span></a>
            {% if loop.index0 == u.add_default %}
            <a class="right add-default"><span class="glyphicon glyphicon-star-empty"></span> 默认地址</a>
            {% else %}
            <a class="right" href="{{ url_for('user.address_default', id=loop.index0)}}"><span>[设为默认地址]</span></a>
            {% endif %}
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">姓名：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{ add.name }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">电话：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{ add.phone }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">地址：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{add.address}}
                </div>
            </div>

        </div>

    </div>
    {% endfor %}
</div>
<script>
    $('#id-button-address-new').click(function(){
        $('#id-div-address-new').toggle()
    })
</script>
{% endblock %}

templates/user/cart.html
{% extends 'base.html' %}
{% block body %}
<div>
    <h1>Shopping Cart</h1>
</div>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="th-col-1">预览</th>
            <th class="th-col-4">商品</th>
            <th class="th-col-1">单价</th>
            <th class="th-col-2">数量</th>
            <th class="th-col-1">小计</th>
        </tr>
    </thead>
    <tbody>
        {% for p in ps %}
        <tr data-uuid={{ p.uuid }}>
            <td>
                <img src="{{ p.pic }}"  class="product-pic-s">
            </td>
            <td>{{ p.name }}</td>
            <td><span class="cart-product-price">{{ p.price }}</span></td>
            <td>
                <div class="quantity-form">
                    <a class="cart-sub" href="#"> - </a>
                    <span class="cart-product-count">{{ p.count }}</span>
                    <a class="cart-add" href="#"> + </a>
                </div>
            </td>
            <td><span class="cart-product-sum">{{ p.sum }}</span></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="panel panel-default">
    <div class="panel-body no-padding">
        {% if (ps|count) == 0 %}
        <div class="left ">
            <div class="empty-cart-title">
                什么？购物车里竟然是空的！
            </div>
            <div class="empty-cart">
                “再忙，也要买点东西犒劳自己~”
            </div>

        </div>
        {% else %}
        <div class="left panel-div">
            总计 <span class="count_num class-cart-count">{{ u.count_num }}</span> 件，
        </div>
        <div class="left panel-div">
            总金额 <span class="count_num class-cart-total">{{ u.count_price }}</span> 元。
        </div>
        {% endif %}
        <a href="{{ url_for('user.check_order') }}" class="btn btn-lg btn-danger right" id="check-order"
        {% if (ps|count) == 0 %}
        disabled
        {% endif %}
        >去结算</a>
    </div>
</div>
<script type="text/javascript" src="{{ url_for('static',filename='js/main.js') }}"></script>

{% endblock %}

templates/user/check_order.html
{% extends 'base.html' %}
{% block body %}
<div class="">
    <div class="stepflex" >
        <dl class="first done">
            <dt class="s-num">1</dt>
            <dd class="s-text">我的购物车</dd>
        </dl>
        <dl class="normal doing">
            <dt class="s-num">2</dt>
            <dd class="s-text">填写核对订单信息</dd>
        </dl>
        <dl class="normal last">
            <dt class="s-num">3</dt>
            <dd class="s-text">成功提交订单</dd>
        </dl>
    </div>
    <h1>结算页
        <span class="count_num"></span>
    </h1>
    <br><br>
</div>

<form action="{{ url_for('user.pay')}}" method="post">

<div class="panel panel-default">
    <div class="panel-body">
        <h4>收货人信息</h4>
        <div class="container-fluid" id=id-div-add-default>
            {% if not u.add %}
            还没有地址，去<a href="{{ url_for('user.address')}}">创建</a>
            {% else %}
            <label>
                <div class="row">
                    <div class="col-xs-1 col-sm-1">
                        <input class="right" type="radio" name="add" value="{{ u.add_default }}" checked required>
                    </div>
                    <div class="col-xs-5 col-sm-2">
                        {{ u.add.name }}
                    </div>
                    <div class="col-xs-5 col-sm-2">
                        {{ u.add.phone }}
                    </div>
                    <div class="col-xs-12 col-sm-7">
                        {{ u.add.address }}
                    </div>
                </div>
            </label>
            <a href="#" id=id-button-more>更多地址</a>
            {% endif %}
        </div>
        <div class="container-fluid" id=id-div-add-more hidden>
            {% for add in u.add_list %}
            <label>
                <div class="row">
                    <div class="col-xs-1 col-sm-1">
                        <input class="right" type="radio" name="add" value="{{ loop.index0 }}">
                    </div>
                    <div class="col-xs-5 col-sm-2">
                        {{ add.name }}
                    </div>
                    <div class="col-xs-5 col-sm-2">
                        {{ add.phone }}
                    </div>
                    <div class="col-xs-12 col-sm-7">
                        {{ add.address }}
                    </div>
                </div>
            </label>
            {% endfor %}
            <a href="#" id=id-button-less>收起地址</a>
        </div>

        <h4>支付方式</h4>
        <div class="container-fluid">
            <label>
                <div class="row">
                    <div class="col-xs-1 col-sm-1">
                        <input class=right type="radio" name="pay" value="alipay" required>
                    </div>
                    <div class="col-xs-10 col-sm-10">
                        支付宝
                    </div>
                </div>
            </label>
            <label>
                <div class="row">
                    <div class="col-xs-1 col-sm-1">
                        <input class=right type="radio" name="pay" value="wechat" >
                    </div>
                    <div class="col-xs-10 col-sm-10">
                        微信支付
                    </div>
                </div>
            </label>
            <label>
                <div class="row">
                    <div class="col-xs-1 col-sm-1">
                        <input class=right type="radio" name="pay" value="face2face">
                    </div>
                    <div class="col-xs-10 col-sm-10">
                        货到付款
                    </div>
                </div>
            </label>
        </div>

        <h4>商品清单</h4>
        <div class="container-fluid">
            <table class="table  table-hover">
                <thead>
                    <tr>
                        <th class="th-col-4">商品</th>
                        <th class="th-col-1">单价</th>
                        <th class="th-col-2">数量</th>
                        <th class="th-col-1">小计</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in ps %}
                    <tr data-id={{ p.uuid }}>
                        <td>{{ p.name }}</td>
                        <td>{{ p.price }}</td>
                        <td>x{{ p.count }}</td>
                        <td>{{ p.sum }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body no-padding">
        <div class="left panel-h4">
            <h4>应付总额 : <span class="count_num">{{ u.count_price }}</span> 元</h4>
        </div>
        <button class="btn btn-lg btn-danger right" id="check-order" {% if not u.add %} disabled {% endif %}>确认付款</button>
    </div>
</div>
</form>

<script>
$('#id-button-more').click(function(){
    $('#id-div-add-more').show()
    $('#id-div-add-default').hide()
})
$('#id-button-less').click(function(){
    $('#id-div-add-more').hide()
    $('#id-div-add-default').show()
})
</script>
{% endblock %}

templates/user/forget_password.html
{% extends 'base.html' %} {% block body %}
<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

<div id="id-div-login" class="div-form sign-flow">
    <form method="post" action="{{ url_for('user.forget_password') }}">
        <div class="group-inputs">
            <input name="username" id="id-input-username" placeholder="用户名" required>
            <input name="email" id="id-input-email" placeholder="邮箱" required>
            <input name="captcha" id="id-input-captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
            <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());" src="/img/captcha" alt="Captcha" class="right" />
        </div>
        <br>
        <button class="btn btn-danger btn-block">找回密码</button>
        <a class="right text-muted" href="{{ url_for('user.login') }}">我又想起来了</a>
    </form>
</div>

<div id="particles-js"></div>
<script type="text/javascript">
    particlesJS.load('particles-js', '/static/js/particles.json');
</script>

{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block body %}
<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

<div id="id-div-login" class="div-form sign-flow">
    <form method="post" action="{{ url_for('user.login') }}">
        <div class="group-inputs">
            <input name="username" id="id-input-username" placeholder="用户名" required>
            <input name="password" id="id-input-password" type="password" placeholder="密码" required>
            <input name="captcha" id="id-input-captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
            <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());"
                 src="/img/captcha" alt="Captcha" class="right"/>
        </div>
        <br>
        <button class="btn btn-default btn-block">登录</button>
        <a class="right text-muted" href="{{ url_for('user.forget_password') }}">忘记密码</a>
    </form>
</div>

<div id="particles-js"></div>
<script type="text/javascript">
    particlesJS.load('particles-js', '/static/js/particles.json');
</script>

{% endblock %}

templates/user/order.html
{% extends 'base.html' %}
{% block body %}
<div>
    <h1>Order Detail</h1>
</div>
<div class="container">

    <div class="row panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="panel-heading-time col-xs-6 col-sm-3">{{ o.ct|time_str }}</div>
                <div class="col-xs-12 col-sm-6">
                    订单号：{{ o.orderNo }}
                </div>
            </div>

        </div>
        <div class="panel-body">
            <h4>当前订单状态 : {{ o.status }}</h4>
            <hr>

            <h4>收货人信息</h4>
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">姓名：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{ o.address.name }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">电话：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{ o.address.phone }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3 col-md-2">
                    <span class="right">地址：</span>
                </div>
                <div class="col-xs-9 col-md-10">
                    {{o.address.address}}
                </div>
            </div>
            <hr>

            <h4>支付方式 : {{ o.payment }}</h4>
            <hr>

            <h4>商品列表</h4>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th class="th-col-1">图片</th>
                        <th class="th-col-4">商品</th>
                        <th class="th-col-1">单价</th>
                        <th class="th-col-1">数</th>
                        <th class="th-col-1">小计</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in o.items %}
                    <tr data-id={{ p.uuid }}>
                        <td>
                            <img src="{{ p.pic }}"  class="product-pic-s">
                        </td>
                        <td>{{ p.name }}</td>
                        <td>{{ p.price }}</td>
                        <td>x{{ p.count }}</td>
                        <td>{{ p.sum }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr>

            <h4>订单总金额 : <span class="count_num">￥ {{ o.amount }}</span></h4>
        </div>
    </div>
</div>

{% endblock %}

templates/user/orders.html
{% extends 'base.html' %}
{% block body %}
<div>
    <h1>Orders List</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-8">
            订单详情
        </div>
        <div class="col-xs-2">
            金额
        </div>
        <div class="col-xs-2">
            状态
        </div>
    </div>
    {% for o in os %}
    <div class="row panel panel-default">
        <div class="panel-heading">
            <span class="panel-heading-time">{{ o.ct|time_str }}</span>
            <a href="{{ url_for('user.order', orderNo=o.orderNo) }}">订单号：{{ o.orderNo }}</a>
        </div>
        <div class="panel-body">
            <div class="col-xs-8">
                {% for i in o.items %}
                <div class="row product-item">
                    <div class="col-xs-3">
                        <img src="{{ i.pic }}"  class="product-pic-s">
                    </div>
                    <div class="col-xs-7">
                        {{ i.name }}
                    </div>
                    <div class="col-xs-2">
                        x{{ i.count }}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-xs-2">
                {{ o.amount }}
            </div>
            <div class="col-xs-2">
                {{ o.status }}
            </div>
        </div>

    </div>
    {% endfor %}
</div>

{% endblock %}

templates/user/profile.html
{% extends 'base.html' %} {% block body %}
<div>
    <h1>Profile</h1>
</div>
<div class="panel panel-default panel-profile">
    <div class="panel-heading">用户名及密码</div>
    <div class="panel-body">
        <form method=POST enctype=multipart/form-data action="{{ url_for('user.profile_update') }}">
            <label for="id-name">用户名</label>
            <input class="form-control" name="username" id=id-name value="{{ u.username }}">
            <label for="id-password">修改密码</label>
            <input class="form-control" name=password id=id-password>
            <label for="id-re-password">重复密码</label>
            <input class="form-control" name=re_password id=id-re-password>
            <hr>
            <button class="btn btn-success btn-block">更新</button>
        </form>
    </div>

</div>
<div class="panel panel-default panel-profile">
    <div class="panel-heading">邮箱信息</div>
    <div class="panel-body">

        <div id=id-div-email-info>
            <label>
            邮箱
            <div class="">
            {{ u.email }}
            </div>
            </label>

            <label>
            验证状态
            {% if u.email_verify %}
            <p class="text-success">
                通过
            </p>
            {% else %}
            <p class="text-danger">
            未验证
            </p>
            {% endif %}
            </label>
            <br>
            <button class="btn btn-info btn-block button-re-verify" id=id-button-re-verify>更新验证</button>
        </div>

        <div id="id-div-email-update" class="" hidden>
            <form method="post" action="{{ url_for('user.update_email') }}" onsubmit="return ajaxFormSubmit()">
                <div class="group-inputs">
                    <input name="password" type=password placeholder="密码" required>
                    <input name="email" placeholder="新邮箱" required>
                    <input name="captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
                </div>
                <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());" src="/img/captcha" alt="Captcha" class="" />
                <br>
                <button class="btn btn-info btn-block" id=id-button-verify type=submit>获取验证邮件</button>
                <button class="btn btn-default btn-block button-re-verify" type=button>取消更新</button>
            </form>
        </div>


    </div>
</div>

<script src="{{ url_for('static', filename='js/profile.js') }}"></script>

{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% block body %}
<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

<div id="id-div-register" class="div-form sign-flow">
    <form method="post" action="{{ url_for('user.register') }}">
        <div class="group-inputs">
            <input name="username" id="id-input-username" placeholder="用户名" required>
            <input name="password" id="id-input-password" placeholder="密码" required>
            <input name="email" id="id-input-email" placeholder="邮箱" required>
            <input name="captcha" id="id-input-captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
            <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());"
                 src="/img/captcha" alt="Captcha" class="right"/>
            <!-- <input name="captcha" id="id-input-mail-code" placeholder="邮箱码" required>
            <button class="btn btn-info right" id=id-button-mail-code type=button>获取</button> -->
        </div>
        <br>
        <button class="btn btn-default btn-block">注册</button>
    </form>
</div>

<div id="particles-js"></div>
<script type="text/javascript">
    particlesJS.load('particles-js', '/static/js/particles.json');
</script>



{% endblock %}

templates/user/reset_password.html
{% extends 'base.html' %} {% block body %}
<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

<div id="id-div-login" class="div-form sign-flow">
    <form method="post" action="{{ url_for('user.reset_password', tb64=tb64) }}">
        <div class="group-inputs">
            <input name="password" id="id-input-password"  placeholder="新密码" required>
        </div>
        <br>
        <button class="btn btn-default btn-block">设置新密码</button>
    </form>
</div>

<div id="particles-js"></div>
<script type="text/javascript">
    particlesJS.load('particles-js', '/static/js/particles.json');
</script>

{% endblock %}